React app setup with rails
intechouse/ror-with-reactjs-boiler-plate pull request #1
Opened 2021-04-14 20:29 UTC by Sajidalirordevloper

React app setup with rails

2021-04-14 20:50 UTC, in-techouse requested changes
Delete the file `app/javascript/components/.keep`

And add all `.keep` files to gitignore

2021-04-14 20:51 UTC, in-techouse commented
Delete the file `app/javascript/packs/hello_react.jsx`

2021-04-14 21:01 UTC, in-techouse requested changes

2021-04-14 21:01 UTC, in-techouse commented on config/webpacker.yml
> +    - .jsx
We will use the `.js` extension.
Remove the `.jsx`.

2021-04-14 21:01 UTC, in-techouse commented on Gemfile
> +gem 'react-rails'
Add version with `=`

2021-04-15 17:04 UTC, in-techouse commented on config/webpacker.yml
> +    - .jsx
@Sajidalirordevloper

2021-04-15 17:04 UTC, in-techouse commented on Gemfile
> +gem 'react-rails'
@Sajidalirordevloper

2021-04-15 17:29 UTC, merged

2021-04-15 17:29 UTC, Sajidalirordevloper commented on config/webpacker.yml
> +    - .jsx
@in-techouse  jsx extension change to js